### ISSUE TITLE
Storage misbehavior

### ISSUE THREAD

**Issue by Shenghan-Chen** [jiaxunsongucb/mini-library#6]
录入图书以后关闭软件再打开就无法搜索到了？试了一下目前的version2似乎也是这样，不确定是否操作步骤有误？ @jiaxunsongucb

**Comment by jiaxunsongucb** [comment]
此错误已经修复。原因是在每次录入图书、借还书后，内存中的df被修改，但是没有正确保存至磁盘文件中。
