### ISSUE TITLE
Online database accuracy

### ISSUE THREAD

**Issue by Shenghan-Chen** [jiaxunsongucb/mini-library#7]
国图1抓取的图书信息个别时候不准确，或者数据库之间有出入。国图2似乎每到凌晨都会挂掉。
<img width="1079" alt="screen shot 2018-06-16 at 1 04 52 am" src="https://user-images.githubusercontent.com/6370162/41490189-8371e7c0-7125-11e8-8b9c-ebb933d159c3.png">

**Comment by jiaxunsongucb** [comment]
是的，国图2的信息会更准确但不稳定，但是国图1的书目会更全。可以考虑改变信息获取的顺序：国图2--> 国图2-->豆瓣
